### PR TITLE
Improve AMI startup script (good PR)

### PR DESCRIPTION
**Pull request by fabricetriboix**
This is mostly about changing the ArkCase admin user password and re-enabling it. Also improvements in services configuration and systemctl handling.

### CODE REVIEW

**Review by kikomanaskov333 — COMMENTED** [review]
@fabricetriboix , I think it would be nice if we define variable 'root_directory=/opt/app/arkcase' at the beginning of the script and use it in every path since it is changing sometimes

**Review by dzdimov — APPROVED** [review]

**Comment by dzdimov** [comment]
Let's add a variable for the path and change the paths as well to include that variable I believe we can merge this

**Review by david-oc-miller — APPROVED** [review]

**Comment by fabricetriboix** [comment]
I agree that adding a `root_directory` variable is a great idea, but don't merge the PR if I need to make some changes! I will create a new branch, make the change and re-submit a new PR.

**Comment by david-oc-miller** [comment]
I merged it before I saw Kristijan's comment :-(

**Pull request merged**
